### ISSUE TITLE
Signal Update (1.204.015) breaks inventory at new game start 

### ISSUE THREAD

**Issue by maniac2003** [austinvaness/BetterInventorySearch#1]
With enabled "BetterInventorySearch" plugin, I have no items in my inventory in a "New Game" start.
The control seat at my respawn pot during EarthLike landing is empty.

**Comment by Kiithnaras** [comment]
This issue is not just one of new games, but existing ones as well, and results in numerous inventories not only being empty but having no capacity.

**Comment by maniac2003** [comment]
It is fixed now.
@austinvaness  Thank you for your fast support!
You are great!
